### PR TITLE
Fix redirects for random-with-units and color-units

### LINKED ISSUE #704: Misbehaving link
The following link:

> https://sass-lang.com/documentation/breaking-changes/random-with-units

...which is found under the **breaking changes** section here:

image

...doesn't work as expected. The HTTP response comes back with a `content-type` header value of `application/octet-stream` which means **the browser opens a File Download dialog rather than loading the page**:

image

### PR DESCRIPTION
**Pull request by Goodwine**
Fixes #704

### CODE REVIEW

File: config.rb [hunk 1]
```diff
@@ -72,8 +72,10 @@
 end
 
 for url in %w[d/random-with-units documentation/breaking-changes/random-with-units
-    d/breaking-changes/color-units documentation/breaking-changes/color-units] do
-  redirect url, to: "/documentation/breaking-changes/function-units"
+    d/color-units documentation/breaking-changes/color-units] do
+  # Middleman requires the origin URL to contain an extension, otherwise it will
```
Comment (nex3) [inline config.rb:76]: I think it's GitHub pages' behavior that's causing this, since we don't run Middleman as a server in production.

**Review by nex3 — APPROVED** [review]
