### PR TITLE
Work around some Color.js bugs that are breaking the playground

### LINKED ISSUE #1444: Certain colors break the playground
It seems that certain color values break the ability for the Sass playground to properly take input and execute the Sass code. To reproduce, open a new playground session, delete the default text, and paste in `@debug rgb(10, 20, 30, 0.1)`. Note that the cursor immediately disappears and isn't possible to move accurately with the keyboard, and various other edits will fail in various strange ways. I believe this is because of errors somewhere in the `Color.js` library which are in turn not being captured correctly.

### PR DESCRIPTION
**Pull request by nex3**
Closes #1444

### CODE REVIEW

File: source/assets/js/playground/color-decorator.ts [hunk 1]
```diff
@@ -77,14 +82,27 @@ class ColorWidget extends WidgetType {
   }
 
   toDOM(): HTMLDivElement {
-    return colorSwatchView(this.color.toString(), Boolean(this.inP3));
+    let colorString: string;
+    try {
+      colorString = this.color.toString();
+    } catch (error) {
+      // Make sure errors like #1444 don't completely break interactivity.
+      console.error(error);
```
Comment (Goodwine) [inline source/assets/js/playground/color-decorator.ts:90]: Do we want to log the error tho?

**Review by Goodwine — APPROVED** [review]
