### PR TITLE
Fix footer not showing the latest versions.

### LINKED ISSUE #1176: Broken latest version links for Current Releases in footer
It appears a recent deployment to the Sass site has broken the latest version links that used to appear next to each of the libraries in the Current Releases section in the site footer. Looking at recent commits, it looks like [4fad520e](https://github.com/sass/sass-site/commit/4fad520e645e090523ee346f8175dbf7c99b2c5b) is the most likely culprit as functions relating to release version information were reworked in it.

### PR DESCRIPTION
**Pull request by Goodwine**
Eleventy expects that default exports are provided with 'module.exports ='. Not with 'export default'.

Fixes #1176

### CODE REVIEW

File: source/_data/releases.ts [hunk 1]
```diff
@@ -106,7 +106,7 @@ async function getLatestVersion(repo: string): Promise<string> {
 /**
  * Returns the version and URL for the latest release of all implementations.
  */
-export default async function (): Promise<Record<string, Release>> {
+module.exports = async function (): Promise<Record<string, Release>> {
```
Comment (nex3) [inline source/_data/releases.ts:109]: Can you add a comment here indicating why `export default` doesn't work? It's what we use everywhere else, so the difference here is conspicuous.

Comment (Goodwine) [reply source/_data/releases.ts:112]: Done, I wasn't sure if this is an issue with Eleventy or LiquidJS, but I documented it as an issue with Liquid

Comment (Goodwine) [reply source/_data/releases.ts:112]: I ended up saying it's Eleventy because AFAICT LiquidJS itself doesn't support JS/TS files as `_data`, that's an Eleventy's feature

**Review by nex3 — APPROVED** [review]
